version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env

  frontend:
    image: streamlit/streamlit
    volumes:
      - ./frontend:/app
    command: streamlit run /app/app.py --server.port 8501
    ports:
      - "8501:8501"